# ABOUTME: Docker Compose configuration for local development
# ABOUTME: Runs desktop environment and services locally

version: '3.8'

services:
  desktop:
    build:
      context: ./containers/desktop
      dockerfile: Dockerfile
    container_name: computer-use-desktop
    ports:
      - "5900:5900"  # VNC
      - "6080:6080"  # noVNC
    environment:
      - DISPLAY=:1
      - VNC_RESOLUTION=1920x1080
      - VNC_PASSWORD=changeme
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - computer-use-network

  vnc-bridge:
    build:
      context: ./backend
      dockerfile: Dockerfile.vnc-bridge
    container_name: computer-use-vnc-bridge
    ports:
      - "8080:8080"
    environment:
      - VNC_HOST=desktop
      - VNC_PORT=5900
      - VNC_PASSWORD=changeme
      - AWS_REGION=us-west-2
    depends_on:
      - desktop
    networks:
      - computer-use-network

  localstack:
    image: localstack/localstack:latest
    container_name: computer-use-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb,secretsmanager
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - computer-use-network

networks:
  computer-use-network:
    driver: bridge

volumes:
  localstack-data: